name = "pickle"
version = "0.2.0"
description = "A parser combinator library for Gleam."
licences = ["MIT"]
repository = { type = "github", user = "patrik-kuehl", repo = "pickle" }
gleam = ">= 1.0.0 and < 2.0.0"

[documentation]
pages = [
    { title = "CHANGELOG", path = "changelog.html", source = "CHANGELOG.md" },
    { title = "LICENSE", path = "license.html", source = "LICENSE.md" },
    { title = " ", path = "#", source = "" },
    { title = "Getting Started", path = "docs/getting-started.html", source = "docs/getting_started.md" },
]

[javascript.deno]
allow_read = true

[dependencies]
gleam_stdlib = ">= 0.37.0 and < 2.0.0"

[dev-dependencies]
simplifile = ">= 1.0.0 and < 2.0.0"
gleeunit = ">= 1.0.0 and < 2.0.0"
